# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sahil Chinoy
email: sahil.chinoy@gmail.com
description: >
  I'm Sahil Chinoy, an undergrad studying physics and economics at UC Berkeley.
  I'm interested in data stories, news apps and interactive graphics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sahilchinoy.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
